export const Food = [
  {
    id: "1",
    foodName: "hotel california",
    price: 125,
    foodImage: "./images/hotel california.jpg",
    category: "Plateaux Sushi",
    quantity: 0,
  },
  {
    id: "2",
    foodName: "sushi express",
    price: 135,
    category: "Plateaux Sushi",
    quantity: 0,
    foodImage: "./images/sushi express.jpg",
  },
  {
    id: "3",
    foodName: "Rolls-Rolls",
    price: 145,
    quantity: 0,
    category: "Plateaux Sushi",
    foodImage: "./images/rolls-rolls.jpg",
  },
  {
    id: "4",
    foodName: "sushi on demand",
    price: 165,
    quantity: 0,
    category: "Plateaux Sushi",
    foodImage: "./images/sushi on demand.jpg",
  },
  {
    id: "5",
    foodName: "sushi mitzva",
    price: 55,
    quantity: 0,
    category: "Plateaux Sushi",
    foodImage: "./images/sushi mitzva.jpg",
  },
  {
    id: "6",
    foodName: "Rouleaux De Printemps Végétarien",
    price: 19,
    quantity: 0,
    category: "Rouleaux De Printemps",
    foodImage: "./images/rouleaux de printemps vegetarien.jpg",
  },
  {
    id: "7",
    foodName: "Rouleaux De Printemps Poulet",
    price: 25,
    quantity: 0,
    category: "Rouleaux De Printemps",
    foodImage: "./images/rouleaux de printemps poulet.jpg",
  },
  {
    id: "8",
    foodName: "Rouleaux De Printemps Viande",
    price: 35,
    quantity: 0,
    category: "Rouleaux De Printemps",
    foodImage: "./images/rouleaux de printemps viande.jpg",
  },
  {
    id: "9",
    foodName: "Rouleaux De Printemps Crevette",
    price: 39,
    quantity: 0,
    category: "Rouleaux De Printemps",
    foodImage: "./images/rouleaux de printemps crevette.jpg",
  },
  {
    id: "10",
    foodName: "Rouleaux De Printemps Saumon",
    price: 59,
    quantity: 0,
    category: "Rouleaux De Printemps",
    foodImage: "./images/rouleaux de printemps saumon.jpg",
  },
  {
    id: "11",
    foodName: "California Saumon",
    price: 35,
    quantity: 0,
    category: "California Rolls",
    foodImage: "./images/california saumon.jpg",
  },
  {
    id: "12",
    foodName: "California Eby Fry",
    price: 35,
    quantity: 0,
    category: "California Rolls",
    foodImage: "./images/california eby fry.jpg",
  },
  {
    id: "13",
    foodName: "California Tiger Rolls",
    price: 39,
    quantity: 0,
    category: "California Rolls",
    foodImage: "./images/california tiger rolls.jpg",
  },
  {
    id: "14",
    foodName: "California Cream Cheese",
    price: 45,
    quantity: 0,
    category: "California Rolls",
    foodImage: "./images/california cream cheese.jpg",
  },
  {
    id: "15",
    foodName: "California Royal Saumon",
    price: 55,
    quantity: 0,
    category: "California Rolls",
    foodImage: "./images/california royal saumon.jpg",
  },
  {
    id: "16",
    foodName: "Spring Roll Poulet",
    price: 39,
    quantity: 0,
    category: "Spring Rolls",
    foodImage: "./images/spring roll poulet.jpg",
  },
  {
    id: "17",
    foodName: "Spring Rolls Crevette",
    price: 45,
    quantity: 0,
    category: "Spring Rolls",
    foodImage: "./images/spring rolls crevette.jpg",
  },
  {
    id: "18",
    foodName: "Spring Rolls Saumon",
    price: 55,
    quantity: 0,
    category: "Spring Rolls",
    foodImage: "./images/spring rolls saumon.jpg",
  },
  {
    id: "19",
    foodName: "Fry Eby Fry",
    price: 45,
    quantity: 0,
    category: "Fry Rolls",
    foodImage: "./images/fry eby fry.jpg",
  },
  {
    id: "20",
    foodName: "Royal Roll",
    price: 55,
    quantity: 0,
    category: "Fry Rolls",
    foodImage: "./images/royal roll.jpg",
  },
  {
    id: "21",
    foodName: "Aromaki Panné",
    price: 59,
    quantity: 0,
    category: "Fry Rolls",
    foodImage: "./images/aromaki panne.jpg",
  },
  {
    id: "22",
    foodName: "Crunchy Fry",
    price: 59,
    quantity: 0,
    category: "Fry Rolls",
    foodImage: "./images/crunchy fry.jpg",
  },
  {
    id: "23",
    foodName: "Pizza Japonaise",
    price: 95,
    quantity: 0,
    category: "Fry Rolls",
    foodImage: "./images/pizza japonaise.jpg",
  },
  {
    id: "24",
    foodName: "Maki Concombre",
    price: 19,
    quantity: 0,
    category: "Makis",
    foodImage: "./images/maki concombre.jpg",
  },
  {
    id: "25",
    foodName: "Maki Avocat",
    price: 25,
    quantity: 0,
    category: "Makis",
    foodImage: "./images/maki avocat.jpg",
  },
  {
    id: "26",
    foodName: "Maki Saumon Cheese",
    price: 35,
    quantity: 0,
    category: "Makis",
    foodImage: "./images/maki saumon cheese.jpg",
  },
  {
    id: "27",
    foodName: "Maki Crevette Pannée",
    price: 35,
    quantity: 0,
    category: "Makis",
    foodImage: "./images/maki crevette pannee.jpg",
  },
  {
    id: "28",
    foodName: "Maki Cheese Flambé",
    price: 39,
    quantity: 0,
    category: "Makis",
    foodImage: "./images/maki cheese flambe.jpg",
  },
  {
    id: "29",
    foodName: "Fried Maki",
    price: 75,
    quantity: 0,
    category: "Makis",
    foodImage: "./images/fried maki.jpg",
  },
  {
    id: "30",
    foodName: "Nigiri Crevettes Cuits",
    price: 25,
    quantity: 0,
    category: "Grands Crus",
    foodImage: "./images/nigiri crevettes cuits.jpg",
  },
  {
    id: "31",
    foodName: "Sushi Saumon",
    price: 35,
    quantity: 0,
    category: "Grands Crus",
    foodImage: "./images/sushi saumon.jpg",
  },
  {
    id: "32",
    foodName: "Sashimi Saumon",
    price: 59,
    quantity: 0,
    category: "Grands Crus",
    foodImage: "./images/sashimi saumon.jpg",
  },
  {
    id: "33",
    foodName: "Tartare De Saumon",
    price: 69,
    quantity: 0,
    category: "Grands Crus",
    foodImage: "./images/tartare de saumon.jpg",
  },
  {
    id: "34",
    foodName: "Tataki De Saumon",
    price: 75,
    quantity: 0,
    category: "Grands Crus",
    foodImage: "./images/tataki de saumon.jpg",
  },
  {
    id: "35",
    foodName: "Chirashi Saumon",
    price: 79,
    quantity: 0,
    category: "Grands Crus",
    foodImage: "./images/chirashi saumon.jpg",
  },
];
